apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zoop.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "zoop.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  ZOOP_POSTGRES_URL: {{ .Values.secrets.postgresUrl | b64enc | quote }}
  ZOOP_TURN_SECRET: {{ .Values.secrets.turnSecret | b64enc | quote }}
